### PR TITLE
Adding gitignore

### PR DESCRIPTION
**Pull request by flampouris**
Adding .gitignore.

### CODE REVIEW

**Comment by flampouris** [comment]
@JessicaMeixner-NOAA This should not have happened, I  forced the update to my fork.

**Comment by JessicaMeixner-NOAA** [comment]
Do you want this put in or not? I'm confused. You mention it in https://github.com/NOAA-EMC/DATM-MOM6-CICE5/pull/9 ?

**Comment by flampouris** [comment]
I want it.

The issue is that I force the push (thinking that this is my fork) and the PR went through without review nor approval. The latter should not have happened.

**Comment by JessicaMeixner-NOAA** [comment]
I don't see it in the develop branch? Did you also un-do this somehow?

**Pull request closed without merging**
